Import('RTT_ROOT')
Import('rtconfig')
from building import *
import os

objs = []
cwd = GetCurrentDir()
list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

group = []
src = []
path = [cwd]

if GetDepend(['JSIR_CARD_USING_WIFI']):
    src += ['udrv_wlan.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
Return('objs')
